### ISSUE TITLE
Downloadable content not working

### ISSUE THREAD

**Issue by AntoinePurnelle** [OpenCageData/leaflet-opencage-geocoding#1]
Hi!

I'm getting thois error when trying the downloaded demo. Search never returns anything.

Thanks ;-)

![image](https://cloud.githubusercontent.com/assets/11534692/6707505/ed60448e-cd67-11e4-8800-f94f68c752f7.png)

**Comment by freyfogle** [comment]
I think you need to replace 'you-api-key-here' with your API key. Please let me know if that solves it.

**Comment by AntoinePurnelle** [comment]
Oh that was a dumb question... Thanks!

**Comment by freyfogle** [comment]
no dumb questions
