### ISSUE TITLE
Is there a way to set house number and street name in the search request?

### ISSUE THREAD

**Issue by jgauna** [OpenCageData/leaflet-opencage-geocoding#10]
I'm wondering if I'm able to set street number and house number as Nominatim requests shows in their API:

```
q=<query>
street=<housenumber> <streetname>
city=<city>
county=<county>
state=<state>
country=<country>
postalcode=<postalcode>
```

This would be better for search results. Sometimes if my query is `main_street<space>house_number` it returns ok and sometime it returns ok if the query is `house_number<space>main_street` and it's very frustrating because these are random scenarios. Maybe it would be better if I can set each option in the request options and not using the query param; something like:

```
        var options = {
          key: '581aaf9dfa71f6d061e92474b1618fd6',
          limit: 6,
          geocodingQueryParams: {
            street_name: 156,
            house_number: 1899,
            no_dedupe: 1,
            bounds: [-58.07545, -34.96995, -57.83169, -34.87143],
            countrycode: 'AR'
          }
        };
```

Regards.

**Comment by mtmail** [comment]
I think this got answered via email back in 2016. The API key no longer exists in our system (we delete those after 6 months of inactivity) so likely obsolete.
Let us know here or https://opencagedata.com/contact if we can help.
