### ISSUE TITLE
Wrong URLs for direct inclusion

### ISSUE THREAD

**Issue by harry-wood** [OpenCageData/leaflet-opencage-geocoding#4]
There's a code snippet given in various places to include the javascript and CSS, if you don't want to download, just include it direct. The URLs seem to be wrong

So that's the snippet in the README here: 
https://github.com/OpenCageData/leaflet-opencage-search/blob/master/README.md#usage
...which is repeated on the homepage leaftlet example http://geocoder.opencagedata.com and on the code page here: http://geocoder.opencagedata.com/code.html#code-leaflet

They don't appear to be valid URLs at all. I tried to work out what they're supposed to be. I think these URLs should work, although I don't know if these are the URLs you _want_ people to link to:

`<link rel="stylesheet" href="http://geocoder.opencagedata.com/css/L.Control.OpenCageData.Search.min.css">`
`<script type="text/javascript" src="http://geocoder.opencagedata.com/js/geocoder.min.js">`

( ...also they don't work due to #2 )

**Comment by freyfogle** [comment]
Hi Harry, sorry for long delay in coming back to you. Thanks for submitting, we're on it.

**Comment by mtmail** [comment]
Well, they are relative paths and assume you downloaded the files. But you're right: it's not intuitive enough. Now we use http://rawgit.com/ to serve absolute URL. I also redid the demo page and it includes an API key.
I'm pretty sure somebody will misuse that: blindly copy&paste and wonder why the API key might be above the daily limit. I guess with almost any code users will forget to read disclaimers so I rather have an easy demo out than adding too many restrictions.

http://opencagedata.github.io/leaflet-opencage-search/

Thanks a lot for the bug reports!
