### ISSUE TITLE
Bug in IE (using 11) - input box doesn't open

### ISSUE THREAD

**Issue by freewheelCarto** [OpenCageData/leaflet-opencage-geocoding#6]
Works fine in Chrome, Firefox, and Safari on IOS.  In IE, the box does not expand to reveal the input when the icon is clicked.  Tested in my application and also with your demo. 

When I revert back to IE 10 and 9, works fine.  Apparently 11 is the issue?  

Any ideas? Thanks!

**Comment by mtmail** [comment]
Thanks for the bug report!

Fixed in https://github.com/OpenCageData/leaflet-opencage-search/commit/21bde1d4c90ecbdd58db7a8fc267c028b66a3bf9 and released version `1.1.2` now.
