### ISSUE TITLE
Marker cannot be removed

### ISSUE THREAD

**Issue by justb4** [OpenCageData/leaflet-opencage-geocoding#7]
When a search has a result the marker with popup text is displayed. After that the marker can never be removed. So a fix could be to make the marker removable. This could be done in various ways. I made a quick fix to add a red remove button in the popup text. Possibly not the most elegant solution. I am open for suggestions. You can see it in action here:

http://app.map5.nl/nltopo (type any Dutch city name e.g. amsterdam)

And the src here: http://app.map5.nl/nltopo/lib/opencage-search/src/js/L.Control.OpenCageSearch.js (lines under JvdB in comments). I can provide a PR.

**Comment by mtmail** [comment]
The best way is to overwrite the `markGeocode` function. https://github.com/perliedman/leaflet-control-geocoder which this module is based on explains it well in the 'Customize' section. This way you can decide not to show a marker, or style it differently or automatically remove it (e.g. on click).

After this fix from April https://github.com/OpenCageData/leaflet-opencage-search/commit/69bcaccac57859c287a1973cabb833083072397e
you no longer have to work about the
`// JvdB sometimes Bounds is not defined`
issue.

**Comment by mtmail** [comment]
added the same instructions to `README` file and pushed version `1.1.2`.

**Comment by justb4** [comment]
Ok, thanks. I use v1.1.2 now as is, only overriding `markGeocode` as follows in my app JS  (for those who would like to do something similar): 

```
        var geocoder = L.Control.openCageSearch(options).addTo(map);

        // Override markGeocode from standard opencage-search version
        geocoder.markGeocode = function (result) {
            // JvdB single instance: singleton
            L.Control.OpenCageSearch.instance = this;

            if (result.bounds) {
                this._map.fitBounds(result.bounds);
            } else {
                this._map.panTo(result.center);
            }

            if (this._geocodeMarker) {
                this._map.removeLayer(this._geocodeMarker);
            }

            // JvdB add button in Popup to remove Marker
            var removeButton = ' <a title="Remove result marker" style="text-decoration: none; font-size: 160%; color: red" href="#" onclick="L.Control.OpenCageSearch.instance._map.removeLayer(L.Control.OpenCageSearch.instance._geocodeMarker)">&otimes;</a>';
            this._geocodeMarker = new L.Marker(result.center)
                .bindPopup(result.name + removeButton)
                .addTo(this._map)
                .openPopup();

            return this;
        };
```
