### ISSUE TITLE
API key public?

### ISSUE THREAD

**Issue by cKlee** [OpenCageData/leaflet-opencage-geocoding#8]
You are suggesting to put the api key in a public script. Maybe you have some advice how to avoid this.

**Comment by freyfogle** [comment]
Hi, thanks for asking. Yes we have advice, from our FAQ, see:
https://geocoder.opencagedata.com/faq#technical

Q: I'm nervous about putting my API key in client side javascript. Won't people steal it?
A: If you put it out there on the internet, yes, it is certainly possible. Our recommendation is to have your javascript send requests to your server where you then call our API. In this way the key is never exposed to the world. We're looking at other ways to limit access, we know keys alone aren't perfect.
